spring:
  cloud:
    stream:
      bindings:
        input:
          destination: sensor-topic
      schema-registry-client:
        endpoint: http://localhost:8990
      schema:
        avro:
          schema-locations: classpath:avro/messages.avsc
server.port: 9999